name       : kservice
version    : 5.96.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kservice-5.96.0.tar.xz : ed99b8ad1ed141fbd38ef1bd0cba5045839c181f3a3d5a672c6a215fcb50e3fd
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
