name       : kservice
version    : 5.105.0
release    : 72
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/kservice-5.105.0.tar.xz : b1010940954040f4a0ed096901e7393f26f262d79b5e904da2247b2602e3c70c
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
