name       : kservice
version    : 5.50.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kservice-5.50.0.tar.xz : 29850fb51f6f4eb757e89ca3ad2baf740aff62f07ecd4de6d6a0d9935f981e78
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
