name       : kservice
version    : 5.49.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kservice-5.49.0.tar.xz : 1fd516e6454523707bd173b253fdde5fd39c0b60b3a943ae096b38540d338bf3
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
