name       : kservice
version    : 5.32.0
release    : 5
source     :
    - http://download.kde.org/stable/frameworks/5.32/kservice-5.32.0.tar.xz : 189c9da0bb48961d16db17540093b68fd4ae061590c34f4cea35dfaba51ab30b
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_TESTING=OFF -DAPPLICATIONS_MENU_NAME="kde-applications.menu" .
build      : |
    %make
install    : |
    %make_install
