name       : kservice
version    : 5.101.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.101/kservice-5.101.0.tar.xz : fc398700243962691119f4653b2c6f4ab379cdcb2728fd309b55fc1d8047c6b2
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
