name       : kservice
version    : 5.39.0
release    : 9
source     :
    - https://download.kde.org/stable/frameworks/5.39/kservice-5.39.0.tar.xz : 149e0320e05abe67140f88a50cbf95d48a075a2996e9b2e3c9d123e6d1417f29
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
