name       : kservice
version    : 5.55.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kservice-5.55.0.tar.xz : 32a11c1c05c43ed803f3c2fb886d75717ab3cbce28d1a325a8272ac1ab9e1d4d
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
