name       : kservice
version    : 5.90.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/kservice-5.90.0.tar.xz : ad4d864f10dcb9b770ab7a1aa44c1024a469c51ee5c89b6ad997d481d7423e88
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
