name       : kservice
version    : 5.84.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/kservice-5.84.0.tar.xz : c2e9c7a87aa7835d7bbfb0f45838a76151733547807a80c86df8307d79287dd1
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
optimize   : lto
builddeps  :
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
