name       : kservice
version    : 5.28.0
release    : 4
source     :
    - http://download.kde.org/stable/frameworks/5.28/kservice-5.28.0.tar.xz : 94d0a1b55f9a2301c1d3e98ff0a0b141764efff2ba0d801ee339e00df81e8c56
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
rundeps    :
    - devel:
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_TESTING=OFF -DAPPLICATIONS_MENU_NAME="kde-applications.menu" .
build      : |
    %make
install    : |
    %make_install
