name       : kservice
version    : 5.35.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.35/kservice-5.35.0.tar.xz : dfc04d85e95a146e4aa77e26b003ebfbba43ee5fb64bd3c821a60dd97acd1625
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_TESTING=OFF -DAPPLICATIONS_MENU_NAME="kde-applications.menu" .
build      : |
    %make
install    : |
    %make_install
