name       : kservice
version    : 5.51.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kservice-5.51.0.tar.xz : ef58a8ceeb6b780e7c6089acbca291e79dc706c55d6fb203daed98d5364b15e0
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
