name       : kservice
version    : 5.44.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kservice-5.44.0.tar.xz : d3477286a3be9cf125155438deaf8c7cd293be1b357d183cb46756e09646f73f
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
