name       : kservice
version    : 5.68.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kservice-5.68.0.tar.xz : c774ce1738081c17e6e105e506aa89c22a9db07e73972d4b18ce733ec8ad0a8a
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
