name       : kservice
version    : 5.46.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kservice-5.46.0.tar.xz : a7f4765cda131b1a21060a4328401381a9346d19cfaf033c7fc12cbc3117a060
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
