name       : kservice
version    : 5.38.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.38/kservice-5.38.0.tar.xz : 2d31c96d8fad235aa2bfc96258ac03d7ec064184fe6a54856f9d7407fbae4a7d
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON -DAPPLICATIONS_MENU_NAME="kde-applications.menu" \
           -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
