name       : kservice
version    : 5.36.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.36/kservice-5.36.0.tar.xz : 90130adca003f0d583afc1031ba1bd303857a938dd9e596127891c07f4da10a6
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : programming
summary    : Plugin framework for desktop services.
description: |
    Plugin framework for desktop services.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
rundeps    :
    - devel :
        - kconfig-devel
        - kcoreaddons-devel
setup      : |
    %cmake -DBUILD_TESTING=OFF -DAPPLICATIONS_MENU_NAME="kde-applications.menu" .
build      : |
    %make
install    : |
    %make_install
